import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { GlobalContextProvider } from "./Context/store";
import { ThemeProvider } from "./Context/theme";
import { ThemeToggle } from "./Components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Hexleap-Assignment</title>
      </head>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <ThemeToggle />
          <GlobalContextProvider >
            {children}
          </GlobalContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
